# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Baptiste Lafoux
subtitle: Welcome to my personal webpage
email: b.lafoux@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my personal page!
url: https://baptistelafoux.github.io # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
twitter_username: baptiste_lfx
github_username: baptiste_lfx
minimal_mistakes_skin: "air"
search: false
atom_feed:
    hide: true
#
# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
# paginate: 5 # amount of posts to show
# paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-include-cache

author:
  avatar: "/assets/images/photo_micro.png"
  bio: "PhD in Fluid Mechanics | Data Science | Oceanography"
  # I am a PhD student at [<ins>PMMH lab</ins>](https://www.pmmh.espci.fr/?-Le-laboratoire-)"
#  location: "Pierre & Marie Curie Campus, Jussieu"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-paper-plane"
      url: "mailto:b.lafoux@gmail.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/BaptisteLafoux"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=ZgGBPKUAAAAJ&hl=en"
    # - label: "Twitter"
    #   icon: "fab fa-fw fa-twitter-square"
    #   url: "https://twitter.com/baptiste_lfx"
    - label: "OrcID"
      icon: "fas fa-fw fa-id-card"
      url: "https://orcid.org/0000-0001-7011-6795"

footer:
  links:
    - label: "Email"
      icon: "fas fa-fw fa-paper-plane"
      url: "mailto:b.lafoux@gmail.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/BaptisteLafoux"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=ZgGBPKUAAAAJ&hl=en"
    # - label: "Twitter"
    #   icon: "fab fa-fw fa-twitter-square"
    #   url: "https://twitter.com/baptiste_lfx"
    - label: "OrcID"
      icon: "fas fa-fw fa-id-card"
      url: "https://orcid.org/0000-0001-7011-6795"

defaults:
  # _posts
  # - scope:
  #     path: ""
  #     type: posts
  #   values:
  #     layout: single
  #     author_profile: true
  #     read_time: true
  #     comments: true
  #     share: true
  #     related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
